#==============#
# Camera Model #
#==============#

# example stereo camera https://github.com/xdspacelab/openvslam/blob/master/example/kitti/KITTI_stereo_04-12.yaml

Camera.name: "NASA"
Camera.setup: "stereo"
#Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fx: 381.36246688113556
Camera.fy: 381.36246688113556
Camera.cx: 320.5
Camera.cy: 240.5

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.000000

Camera.fps: 10.0
Camera.cols: 640
Camera.rows: 480
Camera.focal_x_baseline: 157.29401728003162

Camera.color_order: "RGB"